### ISSUE TITLE
Notes about chef deployment

### ISSUE THREAD

**Issue by AquileaSFX** [kaltura/platform-continuous-integration#4]
Hello, 

ok here are some of my notes, hopping these are useful.

---
<strong>NFS:</strong>
mount point has to be added in the recipe _common like this:

mount "/opt/kaltura/web" do
  device "nfs.decrypting.me:/opt/kaltura/web"
  fstype "nfs"
  options "rw"
  action [:mount, :enable]
end

---
<strong>MYSQL:</strong>
Mysql server needs to be prepared before deployment:

nano /etc/my.cnf

under [mysqld]

open_files_limit = 20000
lower_case_table_names=1
max_allowed_packet = 16M

service mysqld restart

(this can be added to the recipe also)

---
<strong>GENERAL:</strong>
If you are working in a "LiveDVD version" of Centos 6.x
you MUST uninstall libvpx on every node before deployment

yum remove libvpx

---
<strong>GUIDE:</strong>

for DWH there is an error in the guide, there is no recipe called kaltura::nfs
the right line is:
knife node run_list add dwh-node nfs

---
<strong>KMC</strong>

In the preview window when embeding video
there is a list of default players,
but when I select them the preview is all white space.
Ex. widescreen player

**Comment by jessp01** [comment]
Hi Bryan,
Closing this one. If there is still info you'd like to add, please pull.
Thanks,
